# Generated by Django 2.2.6 on 2019-10-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_todo', models.CharField(max_length=400)),
                ('date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
