# Generated by Django 2.1.5 on 2019-10-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitemtype',
            name='emoji',
            field=models.CharField(default='😃', max_length=5),
            preserve_default=False,
        ),
    ]
