# Generated by Django 2.2.6 on 2019-11-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mob_app', '0003_auto_20191107_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='my_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
