# Generated by Django 2.2.7 on 2019-11-22 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('favorited_users', models.ManyToManyField(related_name='favorited_blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
