# Generated by Django 2.2.6 on 2019-11-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shorten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='GetLong',
        ),
    ]
