# Generated by Django 2.2.6 on 2019-11-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortapp', '0002_auto_20191106_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorten',
            old_name='name',
            new_name='URL',
        ),
    ]
