# Generated by Django 2.1.5 on 2019-11-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_url', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
    ]
