# Generated by Django 2.2.6 on 2019-11-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactsPostType',
        ),
        migrations.AlterField(
            model_name='contact',
            name='pnone_number',
            field=models.CharField(max_length=12),
        ),
    ]
