# Generated by Django 2.2.7 on 2019-11-13 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favnumapp', '0002_auto_20191113_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favnum',
            name='reasons',
        ),
        migrations.AddField(
            model_name='favnum',
            name='reasons',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fav_nums', to='favnumapp.FavNumReason'),
            preserve_default=False,
        ),
    ]
