# Generated by Django 2.2.6 on 2019-10-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todoitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=69)),
                ('create_date', models.DateTimeField()),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
