# Generated by Django 2.2.6 on 2019-10-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='status',
            new_name='completion_status',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
