# Generated by Django 2.2.6 on 2019-11-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todopost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='todopost',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
