# Generated by Django 2.1.5 on 2019-10-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todoitemtype_emoji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='type',
            new_name='types',
        ),
    ]
