# Generated by Django 2.2.6 on 2019-10-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_00_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description_text',
            field=models.CharField(max_length=100),
        ),
    ]
