# Generated by Django 2.2.6 on 2019-11-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_long', models.CharField(max_length=500)),
                ('url_code', models.CharField(max_length=20)),
            ],
        ),
    ]
