# Generated by Django 2.1.5 on 2019-10-25 19:14

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('bapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatingPreference',
            new_name='Orientation',
        ),
    ]
