# Generated by Django 2.1.5 on 2019-10-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0002_auto_20191025_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datingprofile',
            name='genders',
            field=models.ManyToManyField(blank=True, to='bapp.Gender'),
        ),
        migrations.AlterField(
            model_name='datingprofile',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='bapp.Orientation'),
        ),
    ]
