# Generated by Django 2.1.5 on 2019-10-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0003_auto_20191025_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='datingprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
