# Generated by Django 2.1.5 on 2019-10-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0004_datingprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datingprofile',
            old_name='preferences',
            new_name='orientations',
        ),
    ]
