# Generated by Django 2.1.5 on 2019-10-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0005_auto_20191025_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datingprofile',
            old_name='profile_pic',
            new_name='picture',
        ),
    ]
